apiVersion: v1
kind: Service
metadata:
  name: {{ include "tvheadend.fullname" . }}
{{- if .Values.service.annotations }}
  annotations:
  {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
  labels:
{{ include "tvheadend.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  loadBalancerIP: {{ .Values.service.address }}
  ports:
    - port: {{ .Values.service.ports.http }}
      targetPort: {{ .Values.service.targetPorts.http }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.ports.htsp }}
      targetPort: {{ .Values.service.targetPorts.htsp }}
      protocol: TCP
      name: htsp  
  selector:
    app.kubernetes.io/name: {{ include "tvheadend.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
