{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mosquitto.fullname" . }}
  labels:
{{ include "mosquitto.labels" . | indent 4 }}
type: Opaque
data:
  {{ .Values.config.certfile }}: {{ .Values.certs.certfile  | b64enc | quote }} 
  {{ .Values.config.keyfile }}: {{ .Values.certs.keyfile  | b64enc | quote }} 
  {{ .Values.config.cafile }}: {{ .Values.certs.cafile  | b64enc | quote }} 
{{- end }}
