{{- $root := . -}}
{{- range $index, $service := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mosquitto.fullname" $root }}-{{ $index }}
{{- if $service.annotations }}
  annotations:
  {{- range $key, $value := $service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
  labels:
{{ include "mosquitto.labels" $root | indent 4 }}
spec:
  type: {{ $service.type }}
  loadBalancerIP: {{ $service.address }}
  ports:
    - port: {{ $service.ports.mqtt }}
      targetPort: {{ $service.targetPorts.mqtt }}
      protocol: TCP
      name: mqtt
    - port: {{ $service.ports.websocket }}
      targetPort: {{ $service.targetPorts.websocket }}
      protocol: TCP
      name: websocket
    - port: {{ $service.ports.mqtts }}
      targetPort: {{ $service.targetPorts.mqtts }}
      protocol: TCP
      name: mqtts
    - port: {{ $service.ports.websockets }}
      targetPort: {{ $service.targetPorts.websockets }}
      protocol: TCP
      name: websockets      
  selector:
    app.kubernetes.io/name: {{ include "mosquitto.name" $root }}
    app.kubernetes.io/instance: {{ $root.Release.Name }}
{{- end }}
