apiVersion: v1
kind: Service
metadata:
  name: {{ include "mosquitto.fullname" . }}
{{- if .Values.service.annotations }}
  annotations:
  {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
  labels:
{{ include "mosquitto.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  loadBalancerIP: {{ .Values.service.address }}
  ports:
    - port: {{ .Values.service.ports.mqtt }}
      targetPort: {{ .Values.service.targetPorts.mqtt }}
      protocol: TCP
      name: mqtt
    - port: {{ .Values.service.ports.websocket }}
      targetPort: {{ .Values.service.targetPorts.websocket }}
      protocol: TCP
      name: websocket
    - port: {{ .Values.service.ports.mqtts }}
      targetPort: {{ .Values.service.targetPorts.mqtts }}
      protocol: TCP
      name: mqtts
    - port: {{ .Values.service.ports.websockets }}
      targetPort: {{ .Values.service.targetPorts.websockets }}
      protocol: TCP
      name: websockets      
  selector:
    app.kubernetes.io/name: {{ include "mosquitto.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
